"""initial enterprise analytics schema

Revision ID: 5a1775288b65
Revises:
Create Date: 2026-07-21 03:30:35.097190
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5a1775288b65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('activation_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_providers',
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('api_base', sa.Text(), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_providers_enterprise_id'), 'ai_providers', ['enterprise_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_enterprise_id'), 'audit_logs', ['enterprise_id'], unique=False)
    op.create_index('ix_audit_tenant_created', 'audit_logs', ['enterprise_id', 'created_at'], unique=False)
    op.create_table('business_entities',
    sa.Column('legal_name', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_entities_enterprise_id'), 'business_entities', ['enterprise_id'], unique=False)
    op.create_table('dashboard_assets',
    sa.Column('bi_adapter', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('embed_url', sa.Text(), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_assets_enterprise_id'), 'dashboard_assets', ['enterprise_id'], unique=False)
    op.create_table('model_assets',
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('input_contract', sa.JSON(), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('parser_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_assets_enterprise_id'), 'model_assets', ['enterprise_id'], unique=False)
    op.create_table('platform_accounts',
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('external_account_id', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_accounts_enterprise_id'), 'platform_accounts', ['enterprise_id'], unique=False)
    op.create_table('semantic_model_versions',
    sa.Column('industry_template', sa.Text(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('quality_gates', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_model_versions_enterprise_id'), 'semantic_model_versions', ['enterprise_id'], unique=False)
    op.create_table('source_definitions',
    sa.Column('file_types', sa.JSON(), nullable=False),
    sa.Column('recognition', sa.JSON(), nullable=False),
    sa.Column('field_aliases', sa.JSON(), nullable=False),
    sa.Column('coverage_time_field', sa.Text(), nullable=False),
    sa.Column('data_granularity', sa.String(length=16), nullable=False),
    sa.Column('arrival_frequency', sa.String(length=16), nullable=False),
    sa.Column('expected_rows', sa.Integer(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('dedupe_keys', sa.JSON(), nullable=False),
    sa.Column('validations', sa.JSON(), nullable=False),
    sa.Column('activation_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('store_field', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_definitions_enterprise_id'), 'source_definitions', ['enterprise_id'], unique=False)
    op.create_index('ix_sources_enterprise_status', 'source_definitions', ['enterprise_id', 'status'], unique=False)
    op.create_table('ai_model_profiles',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('budget_cents', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_model_profiles_enterprise_id'), 'ai_model_profiles', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_ai_model_profiles_provider_id'), 'ai_model_profiles', ['provider_id'], unique=False)
    op.create_table('metric_definitions',
    sa.Column('semantic_model_id', sa.String(length=36), nullable=True),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['semantic_model_id'], ['semantic_model_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enterprise_id', 'key', 'version', name='uq_metric_key_version')
    )
    op.create_index(op.f('ix_metric_definitions_enterprise_id'), 'metric_definitions', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_metric_definitions_semantic_model_id'), 'metric_definitions', ['semantic_model_id'], unique=False)
    op.create_table('model_scope_bindings',
    sa.Column('model_asset_id', sa.String(length=36), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_asset_id'], ['model_assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_scope', 'model_scope_bindings', ['enterprise_id', 'scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('ix_model_scope_bindings_enterprise_id'), 'model_scope_bindings', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_model_scope_bindings_model_asset_id'), 'model_scope_bindings', ['model_asset_id'], unique=False)
    op.create_table('source_bindings',
    sa.Column('source_definition_id', sa.String(length=36), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_definition_id'], ['source_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enterprise_id', 'source_definition_id', 'scope_type', 'scope_id', 'version', name='uq_source_binding_version')
    )
    op.create_index(op.f('ix_source_bindings_enterprise_id'), 'source_bindings', ['enterprise_id'], unique=False)
    op.create_index('ix_source_bindings_scope', 'source_bindings', ['enterprise_id', 'scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('ix_source_bindings_source_definition_id'), 'source_bindings', ['source_definition_id'], unique=False)
    op.create_table('source_schedules',
    sa.Column('source_definition_id', sa.String(length=36), nullable=False),
    sa.Column('cron', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_definition_id'], ['source_definitions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_schedules_enterprise_id'), 'source_schedules', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_source_schedules_source_definition_id'), 'source_schedules', ['source_definition_id'], unique=False)
    op.create_table('stores',
    sa.Column('platform_account_id', sa.String(length=36), nullable=True),
    sa.Column('business_entity_id', sa.String(length=36), nullable=True),
    sa.Column('activation_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_store_id', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_business_entity_id'), 'stores', ['business_entity_id'], unique=False)
    op.create_index(op.f('ix_stores_enterprise_id'), 'stores', ['enterprise_id'], unique=False)
    op.create_index('ix_stores_enterprise_status', 'stores', ['enterprise_id', 'status'], unique=False)
    op.create_index(op.f('ix_stores_platform_account_id'), 'stores', ['platform_account_id'], unique=False)
    op.create_table('ai_task_policies',
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('primary_model_id', sa.String(length=36), nullable=True),
    sa.Column('fallback_model_id', sa.String(length=36), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('redaction_policy', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fallback_model_id'], ['ai_model_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['primary_model_id'], ['ai_model_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_task_policies_enterprise_id'), 'ai_task_policies', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_ai_task_policies_fallback_model_id'), 'ai_task_policies', ['fallback_model_id'], unique=False)
    op.create_index(op.f('ix_ai_task_policies_primary_model_id'), 'ai_task_policies', ['primary_model_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('source_definition_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('raw_object_key', sa.Text(), nullable=False),
    sa.Column('normalized_object_key', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_backfill', sa.Boolean(), nullable=False),
    sa.Column('coverage_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coverage_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_version', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.Integer(), nullable=True),
    sa.Column('quality_result', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('confirmed_by', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_definition_id'], ['source_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enterprise_id', 'source_definition_id', 'source_sha256', name='uq_ingestion_file')
    )
    op.create_index(op.f('ix_ingestion_runs_enterprise_id'), 'ingestion_runs', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_source_definition_id'), 'ingestion_runs', ['source_definition_id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_store_id'), 'ingestion_runs', ['store_id'], unique=False)
    op.create_index('ix_ingestion_tenant_status', 'ingestion_runs', ['enterprise_id', 'status', 'created_at'], unique=False)
    op.create_table('upload_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('source_definition_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('expected_sha256', sa.String(length=64), nullable=False),
    sa.Column('expected_size', sa.Integer(), nullable=False),
    sa.Column('part_size', sa.Integer(), nullable=False),
    sa.Column('received_parts', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_backfill', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_definition_id'], ['source_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_sessions_enterprise_id'), 'upload_sessions', ['enterprise_id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_source_definition_id'), 'upload_sessions', ['source_definition_id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_store_id'), 'upload_sessions', ['store_id'], unique=False)
    op.create_index('ix_upload_tenant_status', 'upload_sessions', ['enterprise_id', 'status'], unique=False)
    op.create_table('certified_aggregates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grain', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('refund', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('fees', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('profit', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enterprise_id', 'ingestion_run_id', 'store_id', 'period_start', 'grain', name='uq_certified_period')
    )
    op.create_index('ix_certified_tenant_period', 'certified_aggregates', ['enterprise_id', 'period_start'], unique=False)
    op.create_table('normalized_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enterprise_id', sa.String(length=36), nullable=False),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('refund', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('advertising_fee', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('shipping_fee', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('product_cost', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_records_run', 'normalized_records', ['ingestion_run_id'], unique=False)
    op.create_index('ix_records_store_time', 'normalized_records', ['store_id', 'occurred_at'], unique=False)
    op.create_index('ix_records_tenant_time', 'normalized_records', ['enterprise_id', 'occurred_at'], unique=False)
    if op.get_bind().dialect.name == 'postgresql':
        tenant_tables = [
            'ai_providers', 'audit_logs', 'business_entities', 'dashboard_assets',
            'model_assets', 'platform_accounts', 'semantic_model_versions',
            'source_definitions', 'ai_model_profiles', 'metric_definitions',
            'model_scope_bindings', 'source_bindings', 'source_schedules', 'stores',
            'ai_task_policies', 'ingestion_runs', 'upload_sessions',
            'certified_aggregates', 'normalized_records',
        ]
        for table in tenant_tables:
            op.execute(sa.text(f'ALTER TABLE {table} ENABLE ROW LEVEL SECURITY'))
            op.execute(sa.text(
                f"CREATE POLICY {table}_tenant_isolation ON {table} "
                "USING (enterprise_id = current_setting('app.current_enterprise_id', true)) "
                "WITH CHECK (enterprise_id = current_setting('app.current_enterprise_id', true))"
            ))
        op.execute(sa.text("""
            CREATE VIEW certified_sales AS
            SELECT enterprise_id, store_id, period_start, grain, row_count, order_count,
                   revenue, refund, fees, profit
            FROM certified_aggregates
        """))
        op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS certified'))
        op.execute(sa.text("""
            CREATE VIEW certified.sales AS
            SELECT enterprise_id, store_id, period_start, grain, row_count, order_count,
                   revenue, refund, fees, profit
            FROM certified_aggregates
        """))
        op.execute(sa.text("""
            DO $$
            BEGIN
              IF EXISTS (SELECT FROM pg_roles WHERE rolname = 'analytics_reader') THEN
                GRANT USAGE ON SCHEMA certified TO analytics_reader;
                GRANT SELECT ON certified.sales TO analytics_reader;
              END IF;
            END
            $$
        """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == 'postgresql':
        op.execute(sa.text('DROP VIEW IF EXISTS certified.sales'))
        op.execute(sa.text('DROP VIEW IF EXISTS certified_sales'))
    op.drop_index('ix_records_tenant_time', table_name='normalized_records')
    op.drop_index('ix_records_store_time', table_name='normalized_records')
    op.drop_index('ix_records_run', table_name='normalized_records')
    op.drop_table('normalized_records')
    op.drop_index('ix_certified_tenant_period', table_name='certified_aggregates')
    op.drop_table('certified_aggregates')
    op.drop_index('ix_upload_tenant_status', table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_store_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_source_definition_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_enterprise_id'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    op.drop_index('ix_ingestion_tenant_status', table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_store_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_source_definition_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_enterprise_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_ai_task_policies_primary_model_id'), table_name='ai_task_policies')
    op.drop_index(op.f('ix_ai_task_policies_fallback_model_id'), table_name='ai_task_policies')
    op.drop_index(op.f('ix_ai_task_policies_enterprise_id'), table_name='ai_task_policies')
    op.drop_table('ai_task_policies')
    op.drop_index(op.f('ix_stores_platform_account_id'), table_name='stores')
    op.drop_index('ix_stores_enterprise_status', table_name='stores')
    op.drop_index(op.f('ix_stores_enterprise_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_business_entity_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_source_schedules_source_definition_id'), table_name='source_schedules')
    op.drop_index(op.f('ix_source_schedules_enterprise_id'), table_name='source_schedules')
    op.drop_table('source_schedules')
    op.drop_index(op.f('ix_source_bindings_source_definition_id'), table_name='source_bindings')
    op.drop_index('ix_source_bindings_scope', table_name='source_bindings')
    op.drop_index(op.f('ix_source_bindings_enterprise_id'), table_name='source_bindings')
    op.drop_table('source_bindings')
    op.drop_index(op.f('ix_model_scope_bindings_model_asset_id'), table_name='model_scope_bindings')
    op.drop_index(op.f('ix_model_scope_bindings_enterprise_id'), table_name='model_scope_bindings')
    op.drop_index('ix_model_scope', table_name='model_scope_bindings')
    op.drop_table('model_scope_bindings')
    op.drop_index(op.f('ix_metric_definitions_semantic_model_id'), table_name='metric_definitions')
    op.drop_index(op.f('ix_metric_definitions_enterprise_id'), table_name='metric_definitions')
    op.drop_table('metric_definitions')
    op.drop_index(op.f('ix_ai_model_profiles_provider_id'), table_name='ai_model_profiles')
    op.drop_index(op.f('ix_ai_model_profiles_enterprise_id'), table_name='ai_model_profiles')
    op.drop_table('ai_model_profiles')
    op.drop_index('ix_sources_enterprise_status', table_name='source_definitions')
    op.drop_index(op.f('ix_source_definitions_enterprise_id'), table_name='source_definitions')
    op.drop_table('source_definitions')
    op.drop_index(op.f('ix_semantic_model_versions_enterprise_id'), table_name='semantic_model_versions')
    op.drop_table('semantic_model_versions')
    op.drop_index(op.f('ix_platform_accounts_enterprise_id'), table_name='platform_accounts')
    op.drop_table('platform_accounts')
    op.drop_index(op.f('ix_model_assets_enterprise_id'), table_name='model_assets')
    op.drop_table('model_assets')
    op.drop_index(op.f('ix_dashboard_assets_enterprise_id'), table_name='dashboard_assets')
    op.drop_table('dashboard_assets')
    op.drop_index(op.f('ix_business_entities_enterprise_id'), table_name='business_entities')
    op.drop_table('business_entities')
    op.drop_index('ix_audit_tenant_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_enterprise_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_providers_enterprise_id'), table_name='ai_providers')
    op.drop_table('ai_providers')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
