import { Check, ChevronRight, CircleAlert, CloudUpload, FileSpreadsheet, Headphones, LoaderCircle, UploadCloud } from 'lucide-react'
import { DragEvent, useEffect, useRef, useState } from 'react'
import { useApp } from '../context/AppContext'
import type { UploadItem } from '../types'
import { chooseDesktopFiles, isDesktop, readDesktopChunk, type DesktopFile } from '../api/desktop'

export default function Upload() {
  const { api, filters } = useApp(); const input=useRef<HTMLInputElement>(null); const [step,setStep]=useState(2); const [items,setItems]=useState<UploadItem[]>([]); const [note,setNote]=useState(''); const [sourceId,setSourceId]=useState('')
  useEffect(()=>{api.list('sources').then(s=>setSourceId(s[0]?.id||'')).catch(()=>setSourceId(''))},[api])
  const addFiles=(files:FileList|File[])=>Array.from(files).filter(f=>/\.(xlsx?|csv|zip)$/i.test(f.name)).forEach(file=>{ const id=crypto.randomUUID(); setItems(v=>[...v,{id,file,state:'uploading',progress:20}]); if(!sourceId){setItems(v=>v.map(x=>x.id===id?{...x,state:'failed',message:'请先由实施人员配置适用的数据来源'}:x));return}api.upload(file,sourceId,filters.storeId||undefined).then(r=>setItems(v=>v.map(x=>x.id===id?{...x,serverId:r.id,state:r.duplicate?'ready':'confirm',progress:100,message:r.duplicate?'这个文件已经收过，不会重复计算':'请确认识别到的经营范围'}:x))).catch(()=>setItems(v=>v.map(x=>x.id===id?{...x,state:'failed',progress:100,message:'上传未完成，请选择一个店铺并检查文件内容'}:x))) })
  const addDesktopFile=async(meta:DesktopFile)=>{const id=crypto.randomUUID();const synthetic=new File([],meta.name);setItems(v=>[...v,{id,file:synthetic,state:'uploading',progress:1}]);try{if(!sourceId)throw new Error('missing source');const session=await api.initiateResumable({filename:meta.name,size:meta.size,sha256:meta.sha256,source_definition_id:sourceId,...(filters.storeId?{store_id:filters.storeId}:{})});if(session.deduplicated){setItems(v=>v.map(x=>x.id===id?{...x,serverId:session.ingestion?.id,state:'ready',progress:100,message:'这个文件已经收过，不会重复计算'}:x));return}if(!session.upload_id)throw new Error('missing upload id');const partSize=session.part_size||4*1024*1024;const complete=new Set(session.received_parts||[]);let part=1;for(let offset=0;offset<meta.size;offset+=partSize,part++){if(!complete.has(part)){const bytes=await readDesktopChunk(meta.path,offset,Math.min(partSize,meta.size-offset));await api.uploadPart(session.upload_id,part,bytes)}const progress=Math.round(Math.min(meta.size,offset+partSize)/meta.size*100);setItems(v=>v.map(x=>x.id===id?{...x,progress}:x))}const run=await api.completeResumable(session.upload_id);setItems(v=>v.map(x=>x.id===id?{...x,serverId:run.id,state:'confirm',progress:100,message:'桌面文件上传完成，请确认经营范围'}:x))}catch{setItems(v=>v.map(x=>x.id===id?{...x,state:'failed',message:sourceId?'上传中断；再次选择同一文件可从已完成部分继续':'请先由实施人员配置适用的数据来源'}:x))}}
  const choose=async()=>{if(isDesktop()){const selected=await chooseDesktopFiles();selected.filter(f=>/\.(xlsx?|csv|zip)$/i.test(f.name)).forEach(f=>void addDesktopFile(f))}else input.current?.click()}
  const drop=(e:DragEvent)=>{e.preventDefault();addFiles(e.dataTransfer.files)}
  const publish=async()=>{const pending=items.filter(i=>i.state==='confirm'&&i.serverId);if(!pending.length)return;for(const item of pending){try{await api.confirmIngestion(item.serverId!,true,note);await api.publishIngestion(item.serverId!);setItems(v=>v.map(x=>x.id===item.id?{...x,state:'ready',message:'已经核对并更新经营看板'}:x))}catch{setItems(v=>v.map(x=>x.id===item.id?{...x,state:'failed',message:'内容核对未通过，已交给实施人员处理'}:x));return}}setStep(3)}
  return <><div className="page-heading upload-title"><div><h1>准备 {filters.period.replace('-','年')}月经营数据</h1><p>只会处理启用日期之后的数据；原文件会安全保存且不会重复计算。</p></div></div><div className="upload-layout"><div className="upload-main"><ol className="steps"><li className={step>=1?'done':''}><span>{step>1?<Check/>:1}</span>选择范围</li><i/><li className={step===2?'active':step>2?'done':''}><span>{step>2?<Check/>:2}</span>添加文件</li><i/><li className={step===3?'active':''}><span>3</span>确认并发布</li></ol>
  {step===2?<><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={drop}><CloudUpload/><h2>把文件拖到这里</h2><p>支持 Excel、CSV 和 ZIP；同一文件不会重复计算</p><button className="button primary" onClick={choose}><UploadCloud size={19}/>选择文件</button><input ref={input} hidden multiple type="file" accept=".xlsx,.xls,.csv,.zip" onChange={e=>e.target.files&&addFiles(e.target.files)}/></div><section className="uploaded"><h2>已添加文件</h2>{items.length===0?<div className="empty-row">还没有添加文件</div>:items.map(item=><article className="file-row" key={item.id}><span className="file-icon"><FileSpreadsheet/></span><div className="file-name"><strong>{item.file.name}</strong><small>{item.file.size?`${(item.file.size/1024).toFixed(0)} KB`:isDesktop()?'桌面文件':'0 KB'}</small></div><span className={`file-status ${item.state}`}>{item.state==='uploading'?<><LoaderCircle className="spin"/>正在检查 {item.progress}%</>:item.state==='ready'?<><Check/>已准备好</>:<><CircleAlert/>{item.state==='failed'?'上传已暂停':'内容需要确认'}</>}</span><small className="file-message">{item.message}</small></article>)}{items.some(item=>item.state==='confirm')&&<button className="button primary continue" onClick={publish}>确认并更新看板<ChevronRight/></button>}</section></>:<section className="confirm-page"><span className="success-seal"><Check/></span><h2>经营看板已经更新</h2><p>{filters.period} 的文件已核对并发布，后续锁定由实施人员完成。</p><button className="button primary" onClick={()=>location.assign('/dashboard')}>查看经营看板</button></section>}</div>
  <aside className="needed"><h2>本月还需要</h2>{['平台费用','商品成本'].map(x=><article key={x}><span className="needed-icon"><FileSpreadsheet/></span><div><strong>{x}</strong><p>请上传或交给实施人员</p></div></article>)}<div className="help-box"><Headphones/><div><h3>没有这些数据？</h3><p>交给实施人员协助准备，我们会尽快帮你完成。</p></div><button className="button primary">交给实施人员<ChevronRight/></button></div></aside></div></>
}
